config/routes.rb
Rails.application.routes.draw do

  get 'home/index'
  root 'dashboards#daily_dash_2018'

  resources :climbs
  resources :workouts
  resources :everydays
  resources :weights
  resources :simple_consumables

  get 'morning_rituals/journal_dash_form' => 'morning_rituals#journal_dash_form'
  resources :morning_rituals
  resources :evening_rituals

  get 'dashboards/daily_dash_2018'
  get 'dashboards/yesterday_dash_2018'
  get 'dashboards/weekly_dash_2018'
  get 'dashboards/morning_dash'
  get 'dashboards/evening_dash'
  get 'dashboards/rituals_dash'
  get 'dashboards/goal_tracking_dash'
  get 'dashboards/scratch_dash'
  get 'dashboards/master_dash'
  get 'dashboards/journal_dash'
  get 'dashboards/health_dash'
  get 'dashboards/success'

  get 'journal_entries/history' => 'journal_entries#history'
  get 'journal_entries/entries_for_journal_dash' => 'journal_entries#entries_for_journal_dash'
  resources :journal_entries

  get 'consumables/meal' => 'consumables#meal'
  get 'consumables/smoothie' => 'consumables#smoothie'
  get 'consumables/omelette' => 'consumables#omelette'
  get 'consumables/mexican' => 'consumables#mexican'
  get 'consumables/food_binge' => 'consumables#food_binge'
  get 'consumables/drink' => 'consumables#drink'
  get 'consumables/drink_water' => 'consumables#drink_water'
  get 'consumables/drink_wine' => 'consumables#drink_wine'
  get 'consumables/drink_coffee' => 'consumables#drink_coffee'
  get 'consumables/drink_binge' => 'consumables#drink_binge'
  post 'consumables/drink_water_now' => 'consumables#drink_water_now'
  post 'consumables/drink_coffee_now' => 'consumables#drink_coffee_now'
  post 'consumables/new_spliff_now' => 'consumables#new_spliff_now'
  get 'consumables/spliff_binge' => 'consumables#spliff_binge'
  resources :consumables

  get 'exercises/copy' => 'exercises#copy'
  get 'exercises/stretch' => 'exercises#stretch'
  get 'exercises/core' => 'exercises#core'
  get 'exercises/run' => 'exercises#run'
  get 'exercises/kettlebell' => 'exercises#kettlebell'
  resources :exercises

  resources :priorities
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/workout.rb
class Workout < ApplicationRecord
	before_create :set_occurrence_date
	before_update :set_occurrence_date

	private

	def set_occurrence_date
		self.occurrence_date = self.occurrence_time.to_date
	end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :set_workout, only: [:show, :edit, :update, :destroy]

  # GET /workouts
  # GET /workouts.json
  def index
    @workouts = Workout.all
  end

  # GET /workouts/1
  # GET /workouts/1.json
  def show
  end

  # GET /workouts/new
  def new
    @workout = Workout.new
  end

  # GET /workouts/1/edit
  def edit
  end

  # POST /workouts
  # POST /workouts.json
  def create
    @workout = Workout.new(workout_params)

    respond_to do |format|
      if @workout.save
        format.html { redirect_to :back, notice: 'Workout was successfully created.' }
        format.json { render :back, status: :created, location: @workout }
      else
        format.html { render :new }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workouts/1
  # PATCH/PUT /workouts/1.json
  def update
    respond_to do |format|
      if @workout.update(workout_params)
        format.html { redirect_to :back, notice: 'Workout was successfully updated.' }
        format.json { render :back, status: :ok, location: @workout }
      else
        format.html { render :edit }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workouts/1
  # DELETE /workouts/1.json
  def destroy
    @workout.destroy
    respond_to do |format|
      format.html { redirect_to workouts_url, notice: 'Workout was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workout
      @workout = Workout.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workout_params
      params.require(:workout).permit(:name, :description, :minutes, :occurrence_time, :occurrence_date)
    end
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/workouts/_dash_form.html.erb
<%= form_for(workout) do |f| %>
  <% if workout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(workout.errors.count, "error") %> prohibited this workout from being saved:</h2>

      <ul>
      <% workout.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<div class="container-fluid">
	<div class="row">
		<div class="col">
			<div class="field">
    			<%= f.label :name %>
    			<%= f.text_field :name %>
  			</div>
		</div>
		<div class="col">
			<div class="field">
		    	<%= f.label :description %>
		    	<%= f.text_area :description %>
			</div>
		</div>	
	</div>
	<div class="row">
		<div class="col">
		    <div class="field">
			    <%= f.label :minutes %>
			    <%= f.number_field :minutes %>
			</div>
		</div>		
		<div class="col">			
			<div class="field">
    			<%= f.label :occurrence_time %>
    			<%= f.datetime_select :occurrence_time %>
  			</div>			
		</div>
	</div>	
	<div class="row">
		<div class="col" align="right">
			<div class="actions" align="right">
				<%= f.submit %>
			</div>
		</div>
	</div>
</div>

<% end %>

app/views/workouts/_form.html.erb
<%= form_for(workout) do |f| %>
  <% if workout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(workout.errors.count, "error") %> prohibited this workout from being saved:</h2>

      <ul>
      <% workout.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :minutes %>
    <%= f.number_field :minutes %>
  </div>

  <div class="field">
    <%= f.label :occurrence_time %>
    <%= f.datetime_select :occurrence_time %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/workouts/edit.html.erb
<h1>Editing Workout</h1>

<%= render 'form', workout: @workout %>

<%= link_to 'Show', @workout %> |
<%= link_to 'Back', workouts_path %>

app/views/workouts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Workouts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Minutes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @workouts.each do |workout| %>
      <tr>
        <td><%= workout.name %></td>
        <td><%= workout.description %></td>
        <td><%= workout.minutes %></td>
        <td><%= link_to 'Show', workout %></td>
        <td><%= link_to 'Edit', edit_workout_path(workout) %></td>
        <td><%= link_to 'Destroy', workout, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Workout', new_workout_path %>

app/views/workouts/new.html.erb
<h1>New Workout</h1>

<%= render 'form', workout: @workout %>

<%= link_to 'Back', workouts_path %>

app/views/workouts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @workout.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @workout.description %>
</p>

<p>
  <strong>Minutes:</strong>
  <%= @workout.minutes %>
</p>

<%= link_to 'Edit', edit_workout_path(@workout) %> |
<%= link_to 'Back', workouts_path %>