config/routes.rb
Rails.application.routes.draw do

  get 'home/index'
  root 'dashboards#daily_dash_2018'

  resources :climbs
  resources :workouts
  resources :everydays
  resources :weights
  resources :simple_consumables

  get 'morning_rituals/journal_dash_form' => 'morning_rituals#journal_dash_form'
  resources :morning_rituals
  resources :evening_rituals

  get 'dashboards/daily_dash_2018'
  get 'dashboards/yesterday_dash_2018'
  get 'dashboards/weekly_dash_2018'
  get 'dashboards/morning_dash'
  get 'dashboards/evening_dash'
  get 'dashboards/rituals_dash'
  get 'dashboards/goal_tracking_dash'
  get 'dashboards/scratch_dash'
  get 'dashboards/master_dash'
  get 'dashboards/journal_dash'
  get 'dashboards/health_dash'
  get 'dashboards/success'

  get 'journal_entries/history' => 'journal_entries#history'
  get 'journal_entries/entries_for_journal_dash' => 'journal_entries#entries_for_journal_dash'
  resources :journal_entries

  get 'consumables/meal' => 'consumables#meal'
  get 'consumables/smoothie' => 'consumables#smoothie'
  get 'consumables/omelette' => 'consumables#omelette'
  get 'consumables/mexican' => 'consumables#mexican'
  get 'consumables/food_binge' => 'consumables#food_binge'
  get 'consumables/drink' => 'consumables#drink'
  get 'consumables/drink_water' => 'consumables#drink_water'
  get 'consumables/drink_wine' => 'consumables#drink_wine'
  get 'consumables/drink_coffee' => 'consumables#drink_coffee'
  get 'consumables/drink_binge' => 'consumables#drink_binge'
  post 'consumables/drink_water_now' => 'consumables#drink_water_now'
  post 'consumables/drink_coffee_now' => 'consumables#drink_coffee_now'
  post 'consumables/new_spliff_now' => 'consumables#new_spliff_now'
  get 'consumables/spliff_binge' => 'consumables#spliff_binge'
  resources :consumables

  get 'exercises/copy' => 'exercises#copy'
  get 'exercises/stretch' => 'exercises#stretch'
  get 'exercises/core' => 'exercises#core'
  get 'exercises/run' => 'exercises#run'
  get 'exercises/kettlebell' => 'exercises#kettlebell'
  resources :exercises

  resources :priorities
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/climb.rb
class Climb < ApplicationRecord
	
	before_create :set_vals_to_zero, :set_total, :set_attempt_total, :set_v_total
	after_create :create_workout_from_climb
	before_update :set_vals_to_zero, :set_total, :set_attempt_total, :set_v_total
	after_update :update_workout_from_climb

	private

	def set_vals_to_zero
		if self.v0s == nil
			self.v0s = 0
		end
		if self.v0_attempts == nil
			self.v0_attempts = 0
		end
		if self.v1s == nil
			self.v1s = 0
		end
		if self.v1_attempts == nil
			self.v1_attempts = 0
		end
		if self.v2s == nil
			self.v2s = 0
		end
		if self.v2_attempts == nil
			self.v2_attempts = 0
		end
		if self.v3s == nil
			self.v3s = 0			
		end
		if self.v3_attempts == nil
			self.v3_attempts = 0
		end
		if self.v4s == nil
			self.v4s = 0
		end
		if self.v4_attempts == nil
			self.v4_attempts = 0
		end
		if self.v5s == nil
			self.v5s = 0			
		end
		if self.v5_attempts == nil
			self.v5_attempts = 0
		end
		if self.v6s == nil
			self.v6s = 0
		end
		if self.v6_attempts == nil
			self.v6_attempts = 0
		end
		if self.v7s == nil
			self.v7s = 0
		end
		if self.v7_attempts == nil
			self.v7_attempts = 0
		end
		if self.v8s == nil
			self.v8s = 0			
		end
		if self.v8_attempts == nil
			self.v8_attempts = 0
		end
		if self.v9s == nil
			self.v9s = 0
		end
		if self.v9_attempts == nil
			self.v9_attempts = 0
		end
		if self.nine_ab == nil
			self.nine_ab = 0
		end
		if self.nine_ab_attempts == nil
			self.nine_ab_attempts = 0
		end
		if self.nine_cd == nil
			self.nine_cd = 0
		end
		if self.nine_cd_attempts == nil
			self.nine_cd_attempts = 0
		end
		if self.ten_ab == nil
			self.ten_ab = 0
		end
		if self.ten_ab_attempts == nil
			self.ten_ab_attempts = 0
		end
		if self.ten_cd == nil
			self.ten_cd = 0
		end
		if self.ten_cd_attempts == nil
			self.ten_cd_attempts = 0
		end
		if self.eleven_ab == nil
			self.eleven_ab = 0
		end
		if self.eleven_ab_attempts == nil
			self.eleven_ab_attempts = 0
		end
		if self.eleven_cd == nil
			self.eleven_cd = 0
		end
		if self.eleven_cd_attempts == nil
			self.eleven_cd_attempts = 0
		end
		if self.twelve_a == nil
			self.twelve_a = 0
		end
		if self.twelve_a_attempts == nil
			self.twelve_a_attempts = 0
		end
		if self.twelve_b == nil
			self.twelve_b = 0
		end
		if self.twelve_b_attempts == nil
			self.twelve_b_attempts = 0
		end
		if self.twelve_c == nil
			self.twelve_c = 0
		end
		if self.twelve_c_attempts == nil
			self.twelve_c_attempts = 0
		end
		if self.twelve_d == nil
			self.twelve_d = 0
		end
		if self.twelve_d_attempts == nil
			self.twelve_d_attempts = 0
		end
	end

	def set_total
		self.total = self.v0s + self.v1s + self.v2s + self.v3s + self.v4s + self.v5s + self.v6s + self.v7s + self.v8s + self.v9s
	end

	def set_attempt_total
		self.attempt_total = self.v0s + self.v0_attempts + self.v1s + self.v1_attempts + self.v2s + self.v2_attempts + self.v3s + self.v3_attempts + self.v4s + self.v4_attempts + self.v5s + self.v5_attempts + self.v6s + self.v6_attempts + self.v7s + self.v7_attempts + self.v8s + self.v8_attempts + self.v9s + self.v9_attempts
	end

	def set_v_total
		self.v_total = self.v0s + self.v1s + self.v2s*2 + self.v3s*3 + self.v4s*4 + self.v5s*5 + self.v6s*6 + self.v7s*7 + self.v8s*8 + self.v9s*9	
	end

	def create_workout_from_climb
		@descrip = self.other + ". " + "#{self.total} total sends on #{self.attempt_total} total attempts. v-total: #{self.v_total}"
		if self.minutes == nil
			Workout.create(name: "climb", description: @descrip, minutes: self.attempt_total*2, occurrence_time: self.created_at, climb_id: self.id)
		else
			Workout.create(name: "climb", description: @descrip, minutes: self.minutes, occurrence_time: self.created_at, climb_id: self.id)
		end
	end

	def update_workout_from_climb
		@workout = Workout.where(climb_id: self.id)
		@descrip = self.other + ". " + "#{self.total} total sends on #{self.attempt_total} total attempts. v-total: #{self.v_total}"
		if self.minutes == nil
			@workout.update(description: @descrip, minutes: self.attempt_total*2, occurrence_time: self.created_at)
		else
			@workout.update(description: @descrip, minutes: self.minutes, occurrence_time: self.created_at)
		end
	end

end

app/controllers/climbs_controller.rb
class ClimbsController < ApplicationController
  before_action :set_climb, only: [:show, :edit, :update, :destroy]

  # GET /climbs
  # GET /climbs.json
  def index
    @climbs = Climb.all
  end

  # GET /climbs/1
  # GET /climbs/1.json
  def show
  end

  # GET /climbs/new
  def new
    @climb = Climb.new
  end

  # GET /climbs/1/edit
  def edit
  end

  # POST /climbs
  # POST /climbs.json
  def create
    @climb = Climb.new(climb_params)

    respond_to do |format|
      if @climb.save
        format.html { redirect_to @climb, notice: 'Climb was successfully created.' }
        format.json { render :show, status: :created, location: @climb }
      else
        format.html { render :new }
        format.json { render json: @climb.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /climbs/1
  # PATCH/PUT /climbs/1.json
  def update
    respond_to do |format|
      if @climb.update(climb_params)
        format.html { redirect_to @climb, notice: 'Climb was successfully updated.' }
        format.json { render :show, status: :ok, location: @climb }
      else
        format.html { render :edit }
        format.json { render json: @climb.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /climbs/1
  # DELETE /climbs/1.json
  def destroy
    @climb.destroy
    respond_to do |format|
      format.html { redirect_to climbs_url, notice: 'Climb was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_climb
      @climb = Climb.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def climb_params
      params.require(:climb).permit(:v0s, :v1s, :v2s, :v3s, :v4s, :v5s, :v6s, :v7s, :v8s, :v9s, :climb_date, :other, :v0_attempts, :v1_attempts, :v2_attempts, :v3_attempts, :v4_attempts, :v5_attempts, :v6_attempts, :v7_attempts, :v8_attempts, :v9_attempts, :minutes, :nine_ab, :nine_cd, :ten_ab, :ten_cd, :eleven_ab, :eleven_cd, :twelve_a, :twelve_b, :twelve_c, :twelve_d, :nine_ab_attempts, :nine_cd_attempts, :ten_ab_attempts, :ten_cd_attempts, :eleven_ab_attempts, :eleven_cd_attempts, :twelve_a_attempts, :twelve_b_attempts, :twelve_c_attempts, :twelve_d_attempts )
    end
end

app/helpers/climbs_helper.rb
module ClimbsHelper
end

app/views/climbs/_form.html.erb
<div class="container-fluid climb-form">


    <%= form_for(climb) do |f| %>
      <% if climb.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(climb.errors.count, "error") %> prohibited this climb from being saved:</h2>

          <ul>
          <% climb.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>






      <div class="row">
        <div class="col">
          <div class="container-fluid">
            <div class="row">
              <div class="col">
                <h4 class="dash-header-2018">Boulder Problems</h4>
              </div>
            </div>
            <div class="row">
              <div class="col">
                <div class="field">
                  <%= f.label :v0s_sent %>
                  <%= f.number_field :v0s %>
                </div>            
              </div>
              <div class="col">  
                <div class="field">
                  <%= f.label :attempted %>
                  <%= f.number_field :v0_attempts %>
                </div>
              </div>   
            </div>
            <div class="row">
              <div class="col">
                <div class="field">
                  <%= f.label :v1s_sent %>
                  <%= f.number_field :v1s %>
                </div>           
              </div>
              <div class="col">  
                <div class="field">
                  <%= f.label :attempted %>
                  <%= f.number_field :v1_attempts %>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col">
                <div class="field">
                  <%= f.label :v2s_sent %>
                  <%= f.number_field :v2s %>
                </div>           
              </div>
              <div class="col">  
                <div class="field">
                  <%= f.label :attempted %>
                  <%= f.number_field :v2_attempts %>
                </div>
              </div>
            </div>             
            <div class="row">
              <div class="col">
                <div class="field">
                  <%= f.label :v3s_sent %>
                  <%= f.number_field :v3s %>
                </div>           
              </div>
              <div class="col">  
                <div class="field">
                  <%= f.label :attempted %>
                  <%= f.number_field :v3_attempts %>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col">
                <div class="field">
                  <%= f.label :v4s_sent %>
                  <%= f.number_field :v4s %>
                </div>           
              </div>
              <div class="col">  
                <div class="field">
                  <%= f.label :attempted %>
                  <%= f.number_field :v4_attempts %>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col">
                <div class="field">
                  <%= f.label :v5s_sent %>
                  <%= f.number_field :v5s %>
                </div>           
              </div>
              <div class="col">  
                <div class="field">
                  <%= f.label :attempted %>
                  <%= f.number_field :v5_attempts %>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col">
                <div class="field">
                  <%= f.label :v6s_sent %>
                  <%= f.number_field :v6s %>
                </div>           
              </div>
              <div class="col">  
                <div class="field">
                  <%= f.label :attempted %>
                  <%= f.number_field :v6_attempts %>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col">
                <div class="field">
                  <%= f.label :v7s_sent %>
                  <%= f.number_field :v7s %>
                </div>           
              </div>
              <div class="col">  
                <div class="field">
                  <%= f.label :attempted %>
                  <%= f.number_field :v7_attempts %>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col">
                <div class="field">
                  <%= f.label :v8s_sent %>
                  <%= f.number_field :v8s %>
                </div>           
              </div>
              <div class="col">  
                <div class="field">
                  <%= f.label :attempted %>
                  <%= f.number_field :v8_attempts %>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col">
                <div class="field">
                  <%= f.label :v9s_sent %>
                  <%= f.number_field :v9s %>
                </div>           
              </div>
              <div class="col">  
                <div class="field">
                  <%= f.label :attempted %>
                  <%= f.number_field :v9_attempts %>
                </div>
              </div>
            </div>                
          </div>          
        </div>
        <div class="col">
          <div class="container-fluid">
            <div class="row">
              <div class="col">
                <h4 class="dash-header-2018">Sport Routes</h4>
              </div>
            </div>
            <div class="row">
              <div class="col">
                <div class="field">
                  <%= f.label "9a/b's sent"   %>
                  <%= f.number_field :nine_ab %>
                </div>            
              </div>
              <div class="col">  
                <div class="field">
                  <%= f.label :attempted %>
                  <%= f.number_field :nine_ab_attempts %>
                </div>
              </div>   
            </div>
            <div class="row">
              <div class="col">
                <div class="field">
                  <%= f.label "9c/d's sent" %>
                  <%= f.number_field :nine_cd %>
                </div>           
              </div>
              <div class="col">  
                <div class="field">
                  <%= f.label :attempted %>
                  <%= f.number_field :nine_cd_attempts %>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col">
                <div class="field">
                  <%= f.label "10a/b's sent" %>
                  <%= f.number_field :ten_ab %>
                </div>           
              </div>
              <div class="col">  
                <div class="field">
                  <%= f.label :attempted %>
                  <%= f.number_field :ten_ab_attempts %>
                </div>
              </div>
            </div>             
            <div class="row">
              <div class="col">
                <div class="field">
                  <%= f.label "10c/d's sent" %>
                  <%= f.number_field :ten_cd %>
                </div>           
              </div>
              <div class="col">  
                <div class="field">
                  <%= f.label :attempted %>
                  <%= f.number_field :ten_cd_attempts %>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col">
                <div class="field">
                  <%= f.label "11a/b's sent" %>
                  <%= f.number_field :eleven_ab %>
                </div>           
              </div>
              <div class="col">  
                <div class="field">
                  <%= f.label :attempted %>
                  <%= f.number_field :eleven_ab_attempts %>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col">
                <div class="field">
                  <%= f.label "11c/d's sent" %>
                  <%= f.number_field :eleven_cd %>
                </div>           
              </div>
              <div class="col">  
                <div class="field">
                  <%= f.label :attempted %>
                  <%= f.number_field :eleven_cd_attempts %>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col">
                <div class="field">
                  <%= f.label "12a's sent" %>
                  <%= f.number_field :twelve_a %>
                </div>           
              </div>
              <div class="col">  
                <div class="field">
                  <%= f.label :attempted %>
                  <%= f.number_field :twelve_a_attempts %>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col">
                <div class="field">
                  <%= f.label "12b's sent" %>
                  <%= f.number_field :twelve_b %>
                </div>           
              </div>
              <div class="col">  
                <div class="field">
                  <%= f.label :attempted %>
                  <%= f.number_field :twelve_b_attempts %>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col">
                <div class="field">
                  <%= f.label "12c's sent" %>
                  <%= f.number_field :twelve_c %>
                </div>           
              </div>
              <div class="col">  
                <div class="field">
                  <%= f.label :attempted %>
                  <%= f.number_field :twelve_c_attempts %>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col">
                <div class="field">
                  <%= f.label "12d's sent" %>
                  <%= f.number_field :twelve_d %>
                </div>           
              </div>
              <div class="col">  
                <div class="field">
                  <%= f.label :attempted %>
                  <%= f.number_field :twelve_d_attempts %>
                </div>
              </div>
            </div>                
          </div>            
        </div>
      </div>

      <div class="field">
        <%= f.label :minutes %>
        <%= f.number_field :minutes %>
      </div>

      <div class="field">
        <%= f.label :location_and_other_notes %>
        <%= f.text_field :other %>
      </div>

      <div class="actions">
        <%= f.submit %>
      </div>
    <% end %>

  
</div>

app/views/climbs/edit.html.erb
<h1>Editing Climb</h1>

<%= render 'form', climb: @climb %>

<%= link_to 'Show', @climb %> |
<%= link_to 'Back', climbs_path %>

app/views/climbs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Climbs</h1>

<table>
  <thead>
    <tr>
      <th>V0s</th>
      <th>V1s</th>
      <th>V2s</th>
      <th>V3s</th>
      <th>V4s</th>
      <th>V5s</th>
      <th>V6s</th>
      <th>V7s</th>
      <th>V8s</th>
      <th>V9s</th>
      <th>total</th>
      <th>v-total</th>
      <th>Notes/Other</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @climbs.order(created_at: :desc).each do |climb| %>
      <tr>
        <td><%= climb.v0s %></td>
        <td><%= climb.v1s %></td>
        <td><%= climb.v2s %></td>
        <td><%= climb.v3s %></td>
        <td><%= climb.v4s %></td>
        <td><%= climb.v5s %></td>
        <td><%= climb.v6s %></td>
        <td><%= climb.v7s %></td>
        <td><%= climb.v8s %></td>
        <td><%= climb.v9s %></td>
        <td><%= climb.total %></td>
        <td><%= climb.v_total %></td>
        <td><%= climb.other %></td>
        <td><%= link_to 'Show', climb %></td>
        <td><%= link_to 'Edit', edit_climb_path(climb) %></td>
        <td><%= link_to 'Destroy', climb, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Climb', new_climb_path %>

app/views/climbs/new.html.erb
<h1>New Climb</h1>

<%= render 'form', climb: @climb %>

<%= link_to 'Back', climbs_path %>

app/views/climbs/show.html.erb
<p id="notice"><%= notice %></p>



<div class="container-fluid" style="max-width:600px;">
  <div class="row">
    <div class="col">
      <p>
        <%= @climb.minutes %> minute <%= @climb.other %><br/>
        <%= @climb.total %> total sends on <%= @climb.attempt_total %> total attempts. v-total: <%= @climb.v_total %> 
      </p>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <h4 class="dash-header-2018">Boulder Problems</h4>
    </div>
  </div>

  <div class="container-fluid">
    <div class="row">
      <div class="col">
        <strong>V0s Sent:</strong>
        <%= @climb.v0s %>    
      </div>
      <div class="col">
        <strong>V0 Attempts:</strong>
        <%= @climb.v0_attempts %>    
      </div>
    </div>    

    <div class="row">
      <div class="col">
        <strong>V1s Sent:</strong>
        <%= @climb.v1s %>    
      </div>
      <div class="col">
        <strong>V1 Attempts:</strong>
        <%= @climb.v1_attempts %>    
      </div>
    </div>

    <div class="row">
      <div class="col">
        <strong>V2s Sent:</strong>
        <%= @climb.v2s %>    
      </div>
      <div class="col">
        <strong>V2 Attempts:</strong>
        <%= @climb.v2_attempts %>    
      </div>
    </div>
    
    <div class="row">  
      <div class="col">
        <strong>V3s Sent:</strong>
        <%= @climb.v3s %>    
      </div>
      <div class="col">
        <strong>V3 Attempts:</strong>
        <%= @climb.v3_attempts %>    
      </div>
    </div>
    
    <div class="row">  
      <div class="col">
        <strong>V4s Sent:</strong>
        <%= @climb.v4s %>    
      </div>
      <div class="col">
        <strong>V4 Attempts:</strong>
        <%= @climb.v4_attempts %>    
      </div>
    </div>
    
    <div class="row">  
      <div class="col">
        <strong>V5s Sent:</strong>
        <%= @climb.v5s %>    
      </div>
      <div class="col">
        <strong>V5 Attempts:</strong>
        <%= @climb.v5_attempts %>    
      </div>
    </div>

    <div class="row">  
      <div class="col">
        <strong>V6s Sent:</strong>
        <%= @climb.v6s %>    
      </div>
      <div class="col">
        <strong>V6 Attempts:</strong>
        <%= @climb.v6_attempts %>    
      </div>
    </div>

    <div class="row">  
      <div class="col">
        <strong>V7s Sent:</strong>
        <%= @climb.v7s %>    
      </div>
      <div class="col">
        <strong>V7 Attempts:</strong>
        <%= @climb.v7_attempts %>    
      </div>
    </div>

    <div class="row">  
      <div class="col">
        <strong>V8s Sent:</strong>
        <%= @climb.v8s %>    
      </div>
      <div class="col">
        <strong>V8 Attempts:</strong>
        <%= @climb.v8_attempts %>    
      </div>
    </div>

    <div class="row">  
      <div class="col">
        <strong>V9s Sent:</strong>
        <%= @climb.v9s %>    
      </div>
      <div class="col">
        <strong>V9 Attempts:</strong>
        <%= @climb.v9_attempts %>    
      </div>
    </div>     
  </div>
        
  <div class="row">
    <div class="col">
      <h4 class="dash-header-2018">Sport Routes</h4>
    </div>
  </div>

  <div class="container-fluid">
    <div class="row">
      <div class="col">
        <strong>9a/bs Sent:</strong>
        <%= @climb.nine_ab %>    
      </div>
      <div class="col">
        <strong>9a/b attempts:</strong>
        <%= @climb.nine_ab_attempts %>    
      </div>
    </div>    

    <div class="row">
      <div class="col">
        <strong>9c/ds Sent:</strong>
        <%= @climb.nine_cd %>    
      </div>
      <div class="col">
        <strong>9c/ds Attempts:</strong>
        <%= @climb.nine_cd_attempts %>    
      </div>
    </div>

    <div class="row">
      <div class="col">
        <strong>10a/bs Sent:</strong>
        <%= @climb.ten_ab %>    
      </div>
      <div class="col">
        <strong>10a/b Attempts:</strong>
        <%= @climb.ten_ab_attempts %>    
      </div>
    </div>
    
    <div class="row">  
      <div class="col">
        <strong>10c/ds Sent:</strong>
        <%= @climb.ten_cd %>    
      </div>
      <div class="col">
        <strong>10c/d Attempts:</strong>
        <%= @climb.ten_cd_attempts %>    
      </div>
    </div>
    
    <div class="row">  
      <div class="col">
        <strong>11a/bs Sent:</strong>
        <%= @climb.eleven_ab %>    
      </div>
      <div class="col">
        <strong>11a/b Attempts:</strong>
        <%= @climb.eleven_ab_attempts %>    
      </div>
    </div>
    
    <div class="row">  
      <div class="col">
        <strong>11c/ds Sent:</strong>
        <%= @climb.eleven_cd %>    
      </div>
      <div class="col">
        <strong>11c/d Attempts:</strong>
        <%= @climb.eleven_cd_attempts %>    
      </div>
    </div>

    <div class="row">  
      <div class="col">
        <strong>12as Sent:</strong>
        <%= @climb.twelve_a %>    
      </div>
      <div class="col">
        <strong>12a Attempts:</strong>
        <%= @climb.twelve_a_attempts %>    
      </div>
    </div>

    <div class="row">  
      <div class="col">
        <strong>12bs Sent:</strong>
        <%= @climb.twelve_b %>    
      </div>
      <div class="col">
        <strong>12b Attempts:</strong>
        <%= @climb.twelve_b_attempts %>    
      </div>
    </div>

    <div class="row">  
      <div class="col">
        <strong>12cs Sent:</strong>
        <%= @climb.twelve_c %>    
      </div>
      <div class="col">
        <strong>12c Attempts:</strong>
        <%= @climb.twelve_c_attempts %>    
      </div>
    </div>

    <div class="row">  
      <div class="col">
        <strong>12ds Sent:</strong>
        <%= @climb.twelve_d %>    
      </div>
      <div class="col">
        <strong>12d Attempts:</strong>
        <%= @climb.twelve_d_attempts %>    
      </div>
    </div>     
  </div>

  <div class="row">
    <div class="col">
      <br/><br/>
      <%= link_to 'Edit', edit_climb_path(@climb) %> |
      <%= link_to 'Back', climbs_path %>      
    </div>
  </div>


</div>