config/routes.rb
Rails.application.routes.draw do

  get 'home/index'
  root 'dashboards#daily_dash_2018'

  resources :climbs
  resources :workouts
  resources :everydays
  resources :weights
  resources :simple_consumables

  get 'morning_rituals/journal_dash_form' => 'morning_rituals#journal_dash_form'
  resources :morning_rituals
  resources :evening_rituals

  get 'dashboards/daily_dash_2018'
  get 'dashboards/yesterday_dash_2018'
  get 'dashboards/weekly_dash_2018'
  get 'dashboards/morning_dash'
  get 'dashboards/evening_dash'
  get 'dashboards/rituals_dash'
  get 'dashboards/goal_tracking_dash'
  get 'dashboards/scratch_dash'
  get 'dashboards/master_dash'
  get 'dashboards/journal_dash'
  get 'dashboards/health_dash'
  get 'dashboards/success'

  get 'journal_entries/history' => 'journal_entries#history'
  get 'journal_entries/entries_for_journal_dash' => 'journal_entries#entries_for_journal_dash'
  resources :journal_entries

  get 'consumables/meal' => 'consumables#meal'
  get 'consumables/smoothie' => 'consumables#smoothie'
  get 'consumables/omelette' => 'consumables#omelette'
  get 'consumables/mexican' => 'consumables#mexican'
  get 'consumables/food_binge' => 'consumables#food_binge'
  get 'consumables/drink' => 'consumables#drink'
  get 'consumables/drink_water' => 'consumables#drink_water'
  get 'consumables/drink_wine' => 'consumables#drink_wine'
  get 'consumables/drink_coffee' => 'consumables#drink_coffee'
  get 'consumables/drink_binge' => 'consumables#drink_binge'
  post 'consumables/drink_water_now' => 'consumables#drink_water_now'
  post 'consumables/drink_coffee_now' => 'consumables#drink_coffee_now'
  post 'consumables/new_spliff_now' => 'consumables#new_spliff_now'
  get 'consumables/spliff_binge' => 'consumables#spliff_binge'
  resources :consumables

  get 'exercises/copy' => 'exercises#copy'
  get 'exercises/stretch' => 'exercises#stretch'
  get 'exercises/core' => 'exercises#core'
  get 'exercises/run' => 'exercises#run'
  get 'exercises/kettlebell' => 'exercises#kettlebell'
  resources :exercises

  resources :priorities
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/priorities_controller.rb
class PrioritiesController < ApplicationController
  before_action :set_priority, only: [:show, :edit, :update, :destroy]

  # GET /priorities
  # GET /priorities.json
  def index
    @priorities = Priority.all
  end

  # GET /priorities/1
  # GET /priorities/1.json
  def show
  end

  # GET /priorities/new
  def new
    @priority = Priority.new
  end

  # GET /priorities/1/edit
  def edit
  end

  # POST /priorities
  # POST /priorities.json
  def create
    @priority = Priority.new(priority_params)

    respond_to do |format|
      if @priority.save
        format.html { redirect_to @priority, notice: 'Priority was successfully created.' }
        format.json { render :show, status: :created, location: @priority }
      else
        format.html { render :new }
        format.json { render json: @priority.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /priorities/1
  # PATCH/PUT /priorities/1.json
  def update
    respond_to do |format|
      if @priority.update(priority_params)
        format.html { redirect_to @priority, notice: 'Priority was successfully updated.' }
        format.json { render :show, status: :ok, location: @priority }
      else
        format.html { render :edit }
        format.json { render json: @priority.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /priorities/1
  # DELETE /priorities/1.json
  def destroy
    @priority.destroy
    respond_to do |format|
      format.html { redirect_to priorities_url, notice: 'Priority was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_priority
      @priority = Priority.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def priority_params
      params.require(:priority).permit(:title, :accomplished)
    end
end

app/helpers/priorities_helper.rb
module PrioritiesHelper
end

app/views/priorities/_form.html.erb
<%= form_for(priority) do |f| %>
  <% if priority.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(priority.errors.count, "error") %> prohibited this priority from being saved:</h2>

      <ul>
      <% priority.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :accomplished %>
    <%= f.check_box :accomplished %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/priorities/edit.html.erb
<h1>Editing Priority</h1>

<%= render 'form', priority: @priority %>

<%= link_to 'Show', @priority %> |
<%= link_to 'Back', priorities_path %>

app/views/priorities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Priorities</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Accomplished</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @priorities.each do |priority| %>
      <tr>
        <td><%= priority.title %></td>
        <td><%= priority.accomplished %></td>
        <td><%= link_to 'Show', priority %></td>
        <td><%= link_to 'Edit', edit_priority_path(priority) %></td>
        <td><%= link_to 'Destroy', priority, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Priority', new_priority_path %>

app/views/priorities/new.html.erb
<h1>New Priority</h1>

<%= render 'form', priority: @priority %>

<%= link_to 'Back', priorities_path %>

app/views/priorities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @priority.title %>
</p>

<p>
  <strong>Accomplished:</strong>
  <%= @priority.accomplished %>
</p>

<%= link_to 'Edit', edit_priority_path(@priority) %> |
<%= link_to 'Back', priorities_path %>