config/routes.rb
Rails.application.routes.draw do

  get 'home/index'
  root 'dashboards#daily_dash_2018'

  resources :climbs
  resources :workouts
  resources :everydays
  resources :weights
  resources :simple_consumables

  get 'morning_rituals/journal_dash_form' => 'morning_rituals#journal_dash_form'
  resources :morning_rituals
  resources :evening_rituals

  get 'dashboards/daily_dash_2018'
  get 'dashboards/yesterday_dash_2018'
  get 'dashboards/weekly_dash_2018'
  get 'dashboards/morning_dash'
  get 'dashboards/evening_dash'
  get 'dashboards/rituals_dash'
  get 'dashboards/goal_tracking_dash'
  get 'dashboards/scratch_dash'
  get 'dashboards/master_dash'
  get 'dashboards/journal_dash'
  get 'dashboards/health_dash'
  get 'dashboards/success'

  get 'journal_entries/history' => 'journal_entries#history'
  get 'journal_entries/entries_for_journal_dash' => 'journal_entries#entries_for_journal_dash'
  resources :journal_entries

  get 'consumables/meal' => 'consumables#meal'
  get 'consumables/smoothie' => 'consumables#smoothie'
  get 'consumables/omelette' => 'consumables#omelette'
  get 'consumables/mexican' => 'consumables#mexican'
  get 'consumables/food_binge' => 'consumables#food_binge'
  get 'consumables/drink' => 'consumables#drink'
  get 'consumables/drink_water' => 'consumables#drink_water'
  get 'consumables/drink_wine' => 'consumables#drink_wine'
  get 'consumables/drink_coffee' => 'consumables#drink_coffee'
  get 'consumables/drink_binge' => 'consumables#drink_binge'
  post 'consumables/drink_water_now' => 'consumables#drink_water_now'
  post 'consumables/drink_coffee_now' => 'consumables#drink_coffee_now'
  post 'consumables/new_spliff_now' => 'consumables#new_spliff_now'
  get 'consumables/spliff_binge' => 'consumables#spliff_binge'
  resources :consumables

  get 'exercises/copy' => 'exercises#copy'
  get 'exercises/stretch' => 'exercises#stretch'
  get 'exercises/core' => 'exercises#core'
  get 'exercises/run' => 'exercises#run'
  get 'exercises/kettlebell' => 'exercises#kettlebell'
  resources :exercises

  resources :priorities
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/everyday.rb
class Everyday < ApplicationRecord
end

app/controllers/everydays_controller.rb
class EverydaysController < ApplicationController
  before_action :set_everyday, only: [:show, :edit, :update, :destroy]

  # GET /everydays
  # GET /everydays.json
  def index
    @everydays = Everyday.all
  end

  # GET /everydays/1
  # GET /everydays/1.json
  def show
  end

  # GET /everydays/new
  def new
    @everyday = Everyday.new
  end

  # GET /everydays/1/edit
  def edit
  end

  # POST /everydays
  # POST /everydays.json
  def create
    @everyday = Everyday.new(everyday_params)

    respond_to do |format|
      if @everyday.save
        format.html { redirect_to :back, notice: 'Everyday was successfully created.' }
        format.json { render :show, status: :created, location: :back }
      else
        format.html { render :new }
        format.json { render json: @everyday.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /everydays/1
  # PATCH/PUT /everydays/1.json
  def update
    respond_to do |format|
      if @everyday.update(everyday_params)
        format.html { redirect_to :back, notice: 'Everyday was successfully updated.' }
        format.json { render :show, status: :ok, location: :back }
      else
        format.html { render :edit }
        format.json { render json: @everyday.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /everydays/1
  # DELETE /everydays/1.json
  def destroy
    @everyday.destroy
    respond_to do |format|
      format.html { redirect_to everydays_url, notice: 'Everyday was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_everyday
      @everyday = Everyday.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def everyday_params
      params.require(:everyday).permit(:read, :cardio, :exercise, :eat_to_plan, :make_money)
    end
end

app/helpers/everydays_helper.rb
module EverydaysHelper
end

app/views/everydays/_daily_dash_form.html.erb
<%= form_for(everyday) do |f| %>
  <% if everyday.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(everyday.errors.count, "error") %> prohibited this everyday from being saved:</h2>

      <ul>
      <% everyday.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table>
    <tr>
      <td>
          <div class="field">
            <%= f.check_box :read %>
          </div>
      </td>
      <td valign="top">
        Read
      </td>
    </tr>
    <tr>
      <td>
        <div class="field">
          <%= f.check_box :cardio %>
        </div>      
      </td>
      <td valign="top">
        Cardio
      </td>
    </tr>
    <tr>
      <td>
        <div class="field">
          <%= f.check_box :exercise %>
        </div>       
      </td>
      <td valign="top">
        Exercise
      </td>
    </tr>
    <tr>
      <td>
        <div class="field">
          <%= f.check_box :eat_to_plan %>
        </div>      
      </td>
      <td valign="top">
        Eat to plan
      </td>
    </tr>
    <tr>
      <td>
        <div class="field">
          <%= f.check_box :make_money %>
        </div>          
      </td>
      <td valign="top">
        Make Money
      </td>
    </tr>    
  </table>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/everydays/_daily_dash_show.html.erb
<p>
  <strong>Read:</strong> <%= @todays_everyday.read %>
  <br />
  <strong>Cardio:</strong> <%= @todays_everyday.cardio %>
  <br />
  <strong>Exercise:</strong> <%= @todays_everyday.exercise %>
  <br />
  <strong>Eat to plan:</strong> <%= @todays_everyday.eat_to_plan %>
  <br />
  <strong>Make money:</strong> <%= @todays_everyday.make_money %>
  <br /><br />
  <u>
		<%= link_to "Edit these Dos", edit_everyday_path(:controller => "everydays", :action => "edit", :id => @todays_everyday.id) %>
	</u>  
</p>

app/views/everydays/_form.html.erb
<%= form_for(everyday) do |f| %>
  <% if everyday.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(everyday.errors.count, "error") %> prohibited this everyday from being saved:</h2>

      <ul>
      <% everyday.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :read %>
    <%= f.check_box :read %>
  </div>

  <div class="field">
    <%= f.label :cardio %>
    <%= f.check_box :cardio %>
  </div>

  <div class="field">
    <%= f.label :exercise %>
    <%= f.check_box :exercise %>
  </div>

  <div class="field">
    <%= f.label :eat_to_plan %>
    <%= f.check_box :eat_to_plan %>
  </div>

  <div class="field">
    <%= f.label :make_money %>
    <%= f.check_box :make_money %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/everydays/edit.html.erb
<h1>Editing Everyday</h1>

<%= render 'form', everyday: @everyday %>

<%= link_to 'Show', @everyday %> |
<%= link_to 'Back', everydays_path %>

app/views/everydays/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Everydays</h1>

<table>
  <thead>
    <tr>
      <th>Read</th>
      <th>Cardio</th>
      <th>Exercise</th>
      <th>Eat to plan</th>
      <th>Make money</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @everydays.each do |everyday| %>
      <tr>
        <td><%= everyday.read %></td>
        <td><%= everyday.cardio %></td>
        <td><%= everyday.exercise %></td>
        <td><%= everyday.eat_to_plan %></td>
        <td><%= everyday.make_money %></td>
        <td><%= link_to 'Show', everyday %></td>
        <td><%= link_to 'Edit', edit_everyday_path(everyday) %></td>
        <td><%= link_to 'Destroy', everyday, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Everyday', new_everyday_path %>

app/views/everydays/new.html.erb
<h1>New Everyday</h1>

<%= render 'form', everyday: @everyday %>

<%= link_to 'Back', everydays_path %>

app/views/everydays/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Read:</strong>
  <%= @everyday.read %>
</p>

<p>
  <strong>Cardio:</strong>
  <%= @everyday.cardio %>
</p>

<p>
  <strong>Exercise:</strong>
  <%= @everyday.exercise %>
</p>

<p>
  <strong>Eat to plan:</strong>
  <%= @everyday.eat_to_plan %>
</p>

<p>
  <strong>Make money:</strong>
  <%= @everyday.make_money %>
</p>

<%= link_to 'Edit', edit_everyday_path(@everyday) %> |
<%= link_to 'Back', everydays_path %>